# Generated by Django 5.2.14 on 2026-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_add_cloudinary_storage_to_message_image'),
        ('users', '0008_userprofile_users_userp_pseudo_c7f322_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient'], name='inbox_messa_recipie_62ba10_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='inbox_messa_is_read_faef9b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_archived'], name='inbox_messa_is_arch_5043f3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_reported'], name='inbox_messa_is_repo_ff4a09_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='inbox_messa_created_32fc58_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='inbox_messa_recipie_5396a2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'created_at'], name='inbox_messa_recipie_51e010_idx'),
        ),
    ]
