# Generated by Django 5.2.14 on 2026-09-15 23:22

import apps.inbox.models
import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_message_archived_at_message_is_archived_and_more'),
        ('users', '0009_blockedsender_friendship_invitation_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_session_token', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('revealed', 'Identité révélée'), ('closed', 'Clos')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('initial_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='inbox.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_threads', to='users.userprofile')),
                ('revealed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revealed_threads', to='users.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('recipient', 'Destinataire'), ('anonymous', 'Expéditeur anonyme')], max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='thread_media/')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('delivered', 'Délivré'), ('read', 'Lu')], default='sent', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.anonymousthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinned_for_user1', models.BooleanField(default=False)),
                ('pinned_for_user2', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to='users.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='users.userprofile')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='conversation_media/')),
                ('media_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Message vocal'), ('doc', 'Document')], default='text', max_length=15)),
                ('voice_duration', models.IntegerField(default=0, help_text='Durée audio en secondes')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted_for_all', models.BooleanField(default=False)),
                ('deleted_for_user1', models.BooleanField(default=False)),
                ('deleted_for_user2', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('delivered', 'Délivré'), ('read', 'Lu')], default='sent', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='inbox.conversationmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_conversation_messages', to='users.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='inbox.conversationmessage')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='inbox.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('invitation_received', 'Nouvelle invitation'), ('invitation_accepted', 'Invitation acceptée'), ('anonymous_reply', 'Réponse dans fil anonyme'), ('new_message', 'Nouveau message privé'), ('story_like', 'Like sur story'), ('story_reaction', 'Réaction sur story'), ('group_message', 'Nouveau message de groupe')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('target_url', models.CharField(default='/', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to='users.userprofile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='stories/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('text', 'Texte')], default='image', max_length=15)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #FF4565 0%, #FF8038 100%)', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.inbox.models.default_story_expiry)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='users.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_fully_loaded', models.BooleanField(default=True)),
                ('liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='inbox.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='users.userprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='anonymousthread',
            index=models.Index(fields=['recipient', 'status'], name='inbox_anony_recipie_02eb84_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousthread',
            index=models.Index(fields=['sender_session_token'], name='inbox_anony_sender__0e7c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousthread',
            index=models.Index(fields=['updated_at'], name='inbox_anony_updated_e978b6_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousthreadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='inbox_anony_thread__626a36_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user1', 'last_message_at'], name='inbox_conve_user1_i_115ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user2', 'last_message_at'], name='inbox_conve_user2_i_00e1f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='inbox_conve_convers_9f3b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['sender'], name='inbox_conve_sender__f1bbac_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='inbox_messa_message_702a24_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['conversation_message'], name='inbox_messa_convers_d12304_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='inbox_notif_recipie_03ebdd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='inbox_notif_recipie_1ea77f_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', 'expires_at'], name='inbox_story_user_id_31ebcc_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='inbox_story_expires_5ed716_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', 'viewer'], name='inbox_story_story_i_e21305_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('story', 'viewer')},
        ),
    ]
