# Generated by Django 5.2.14 on 2026-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_linkpreview_anonymousthread_anonymousthreadmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousthreadmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thread_media/'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='conversation_media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
