# Generated by Django 5.2.14 on 2026-09-18 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_alter_anonymousthreadmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='link_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inbox.linkpreview'),
        ),
    ]
