# Generated by Django 6.0.5 on 2026-05-13 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groups.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='last_pseudo_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
