# Generated by Django 6.0.5 on 2026-05-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ephemeral_mode',
            field=models.CharField(choices=[('none', 'Désactivé'), ('1h', '1 heure'), ('24h', '24 heures')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='groups.groupmessage')),
            ],
            options={
                'unique_together': {('message', 'session_token', 'emoji')},
            },
        ),
    ]
