# Generated by Django 5.2.14 on 2026-05-21 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_ephemeral_mode_groupmessagereaction'),
        ('users', '0008_userprofile_users_userp_pseudo_c7f322_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='last_read_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='last_scroll_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['link_id'], name='groups_grou_link_id_09f409_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['last_activity'], name='groups_grou_last_ac_241ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group'], name='groups_grou_group_i_f2f5de_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['created_at'], name='groups_grou_created_5429e1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender_session_token'], name='groups_grou_sender__3f89fd_idx'),
        ),
        migrations.AddIndex(
            model_name='groupparticipant',
            index=models.Index(fields=['group', 'session_token'], name='groups_grou_group_i_2b582e_idx'),
        ),
        migrations.AddIndex(
            model_name='groupparticipant',
            index=models.Index(fields=['last_read_message_id'], name='groups_grou_last_re_1231db_idx'),
        ),
    ]
