# Generated by Django 5.2.14 on 2026-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_last_activity_groupmessage_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
