# Generated by Django 5.2.14 on 2026-09-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_archived_at_group_is_archived'),
        ('users', '0009_blockedsender_friendship_invitation_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('anonymous', 'Anonyme (pseudos aléatoires)'), ('known', 'Connu (identités réelles)')], default='anonymous', max_length=15),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type'], name='groups_grou_group_t_aa4704_idx'),
        ),
    ]
