# Generated by Django 5.2.14 on 2026-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_group_type_groupparticipant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_messages/'),
        ),
    ]
