# Generated by Django 6.0.5 on 2026-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content_mode',
            field=models.CharField(choices=[('text', 'Messages texte uniquement'), ('images', 'Images uniquement'), ('both', 'Les deux')], default='both', help_text='Choix unique: texte, images, ou les deux', max_length=10),
        ),
    ]
