# Generated by Django 6.0.5 on 2026-05-09 23:02

import cloudinary_storage.storage
import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('users', 'UserProfile')
    for row in MyModel.objects.all():
        row.reconnect_token = uuid.uuid4()
        row.save(update_fields=['reconnect_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_content_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reconnect_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='reconnect_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profiles/'),
        ),
    ]
