# Generated by Django 6.0.5 on 2026-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_reconnect_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
