# Generated by Django 6.0.5 on 2026-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID de chat Telegram pour les notifications', max_length=100, null=True),
        ),
    ]
