# Generated by Django 5.2.14 on 2026-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['pseudo'], name='users_userp_pseudo_c7f322_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['link_id'], name='users_userp_link_id_72f1aa_idx'),
        ),
    ]
