# Generated by Django 5.2.14 on 2026-09-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_users_userp_pseudo_c7f322_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocked_session_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('blocked', 'Bloquée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_private_pro',
            field=models.BooleanField(default=False, help_text='Joignable uniquement via lien direct ou QR code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_searchable',
            field=models.BooleanField(default=True, help_text='Être trouvable dans la recherche publique'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_color',
            field=models.CharField(default='#FF4565', help_text='Couleur de thème dominante', max_length=30),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_searchable'], name='users_userp_is_sear_a48955_idx'),
        ),
        migrations.AddField(
            model_name='blockedsender',
            name='blocked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='blockedsender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_senders', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='blockedsender',
            index=models.Index(fields=['user', 'blocked_session_token'], name='users_block_user_id_6f936e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedsender',
            index=models.Index(fields=['user', 'blocked_user'], name='users_block_user_id_52f85e_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1', 'user2'], name='users_frien_user1_i_482d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['created_at'], name='users_frien_created_3b3c7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['to_user', 'status'], name='users_invit_to_user_52a72c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['from_user', 'status'], name='users_invit_from_us_728736_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['created_at'], name='users_invit_created_29b66d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('from_user', 'to_user')},
        ),
    ]
