BIZARRE_NAMES = [
    # --- ANIMAUX & CRÉATURES ---
    "Cactus Radioactif", "Pingouin de l'Espace", "Ombre Dansante", "Pizza Volante", "Licorne de Minuit",
    "Robot Mélancolique", "Fantôme Gourmand", "Ninja Invisible", "Banane Cosmique", "Nuage de Sucre",
    "Écureuil Ninja", "Dragon en Pyjama", "Fromage Volant", "Singe Astronaute", "Carotte Mutante",
    "Vampire Solaire", "Zombi Végétalien", "Alien Poli", "Yéti Rose", "Loup-Garou Timide",
    "Ananas Géant", "Pastèque Galactique", "Chat de Schrödinger", "Rat de Bibliothèque", "Hibou insomniaque",
    "Tortue Rapide", "Lièvre Paresseux", "Éléphant Miniature", "Souris de Laboratoire", "Hamster Kung-Fu",
    "Koala Électrique", "Panda Roux Farceur", "Lémurien Disco", "Paresseux Pressé", "Autruche Volante",
    "Flamant Rose en Ski", "Pingouin de Désert", "Ours Polaire Tropical", "Morse Chantant", "Phoque Jongleur",
    "Baleine Volante", "Dauphin Lunaire", "Requin Souriant", "Méduse Éclatante", "Crabe Musicien",
    "Homard de Luxe", "Crevette Géante", "Pieuvre Artiste", "Étoile de Mer Filante", "Hippocampe de Course",
    "Phénix de Glace", "Griffon Bavard", "Minotaure Perdu", "Centaure Moderne", "Sirène Terrestre",
    "Troll Gentil", "Gnome Farceur", "Lutin Malicieux", "Fée Grincheuse", "Magicien Raté",
    "Sorcière Écolo", "Alchimiste Fou", "Chevalier en Carton", "Princesse Rebelle", "Roi Sans Couronne",
    "Bouffon Sérieux", "Marchand de Sable", "Père Noël d'Été", "Lapin de Pâques d'Hiver", "Citrouille Vivante",
    "Épouvantail Amical", "Squelette Dansant", "Momie Bavarde", "Spectre Silencieux", "Esprit Frappeur",
    "Génie de la Lampe", "Lampe de Génie", "Tapis Volant", "Balai Magique", "Chaudron Bouillonnant",
    "Potion Mystère", "Cristal de Lune", "Soleil de Minuit", "Étoile Perdue", "Comète Vagabonde",
    "Galaxie Perdue", "Univers Parallèle", "Trou Noir Lumineux", "Supernova Calme", "Nébuleuse Colorée",
    "Planète Inconnue", "Astéroïde Farceur", "Météore Filant", "Fusée en Carton", "Soucoupe Volante",
    "Martien Vert Pomme", "Vénusien Bleu Marine", "Jupiterien Géant", "Saturnien à Anneaux", "Neptunien Aquatique",
    "Plutonien Oublié", "Mercure de Glace", "Terrien de l'Espace", "Cosmonaute Perdu", "Sonde Spatiale",
    "Satellite Espion", "Télescope Curieux", "Microscope Géant", "Boussole Folle", "Horloge à l'Envers",
    "Calendrier de Demain", "Journal d'Hier", "Livre Sans Fin", "Plume d'Or", "Encrier Vide",
    "Parchemin Ancien", "Carte au Trésor", "Coffre Vide", "Clé Perdue", "Porte Secrète",
    "Labyrinthe Sans Sortie", "Escalier de Nuages", "Fenêtre sur l'Infini", "Miroir Déformant", "Cadre Vide",
    "Table Tournante", "Chaise Volante", "Lit de Plumes", "Armoire Magique", "Rideau de Fumée",
    "Lampe à Huile de Coude", "Bougie Éternelle", "Allumette Mouillée", "Feu de Glace", "Eau Sèche",
    "Air Solide", "Terre Volante", "Métal Liquide", "Pierre Précieuse de Plastique", "Diamant de Verre",
    "Or de Fou", "Argent de Sable", "Bronze de Papier", "Fer de Bois", "Cuivre de Plume",
    "Musique Silencieuse", "Chant Muet", "Danse Immobile", "Peinture Invisible", "Sculpture de Vent",
    "Poème Sans Mots", "Histoire Sans Fin", "Légende Oubliée", "Mythe Moderne", "Conte de Fées Réel",
    "Rêve Éveillé", "Cauchemar Doux", "Illusion Réelle", "Mirage Tangible", "Réalité Virtuelle",
    "Robot de Chair", "Humain d'Acier", "Cyborg de Nature", "Androïde de Bois", "Machine à Rêver",
    "Moteur à Air", "Pile Inépuisable", "Fil Éternel", "Boulon Magique", "Vis Sans Fin",
    "Marteau de Plume", "Scie Musicale", "Tournevis Sonique", "Pince de Crabe", "Clé de Sol",
    "Note de Musique Volante", "Accord Perdu", "Mélodie Mystère", "Rythme Fou", "Silence Bruyant",
    "Couleur Invisible", "Lumière Noire", "Ombre Lumineuse", "Reflet de Soi", "Écho du Futur",
    "Murmure du Vent", "Cri de la Mer", "Souffle de la Terre", "Larme de Ciel", "Rire de Lune",

    # --- FOOTBALLEURS (100) ---
    "Messi l'Extraterrestre", "CR7 le Robot", "Mbappé la Fusée", "Neymar le Magicien", "Haaland le Cyborg",
    "Benzema le Nueve", "Modric l'Éternel", "Zidane le Maestro", "Pelé le Roi", "Maradona la Main de Dieu",
    "Ronaldinho le Sourire", "Ronaldo le Phénomène", "Ibrahimovic le Lion", "Lewandowski la Machine",
    "Salah le Pharaon", "Mané le Lion de la Teranga", "Mahrez le Fennec", "Eto'o le Pitchichi", "Drogba la Légende",
    "Henry le Titi", "Griezmann le Petit Prince", "Pogba la Pioche", "Kanté le Poumon", "Lloris le Mur",
    "Varane le Roc", "Casemiro le Tank", "Vinicius le Danseur", "Rodrygo l'Éclair", "Bellingham le Phénomène",
    "Pedri l'Artiste", "Gavi le Guerrier", "Busquets la Sentinelle", "Iniesta l'Illusionniste", "Xavi le Cerveau",
    "Puyol le Lion de Catalogne", "Piqué le Président", "Ramos le Gladiateur", "Marcelo le Funambule",
    "Dani Alves le Collectionneur", "Courtois le Géant", "Oblak le Mur de Madrid", "Ter Stegen le Mur Allemand",
    "Neuer le Libéro", "Buffon l'Éternel", "Casillas le Saint", "Van Dijk le Colosse", "Ruben Dias le Roc",
    "Kimmich le Polyvalent", "De Bruyne l'Architecte", "Bernardo Silva le Lutin", "Bruno Fernandes le Magnifico",
    "Son le Guerrier de Séoul", "Harry Kane le Prince", "Rashford le Philanthrope", "Foden le Joyau",
    "Saka l'Étoile", "Rice le Pilier", "Mount le Créateur", "James le Puissant", "Chilwell le Rapide",
    "Robertson le Guerrier Écossais", "Trent l'Artilleur", "Alisson le Sauveur", "Ederson le Relanceur",
    "Fabinho le Phare", "Thiago l'Élégant", "Henderson le Capitaine", "Firmino le Magicien", "Jota le Buteur",
    "Darwin le Sniper", "Luis Diaz le Dynamiteur", "Nunez le Lion", "Valverde le Faucon", "Camavinga le Futur",
    "Tchouaméni le Mur", "Dembélé le Dribbleur", "Raphinha le Gaucher", "Ferran le Requin", "Lewy le Polonais",
    "Müller l'Interpréteur d'Espace", "Musiala le Bambi", "Sane l'Éclair", "Coman le Finaleur", "Gnabry le Chef",
    "Davies le Canadien Volant", "Upamecano le Mur", "Pavard le Volleyeur", "Theo Hernandez le Turbo",
    "Maignan le Magicien", "Giroud le Phénix", "Leao le Sourire de Milan", "Osimhen le Masqué", "Kvaratskhelia le Kvaradona",
    "Dybala la Joya", "Lautaro le Toro", "Di Maria le Fideo", "Enzo le Chef d'Orchestre", "Julian Alvarez l'Araignée",
    "Hakimi le Lion de l'Atlas", "Ziyech le Magicien du Maroc", "Bounou le Mur Marocain", "Amrabat le Guerrier",

    # --- ACTEURS & CÉLÉBRITÉS (150) ---
    "Brad Pitt le Beau Gosse", "Tom Cruise l'Intrépide", "Leonardo DiCaprio le Loup", "Johnny Depp le Pirate",
    "Will Smith le Prince", "Dwayne Johnson le Rocher", "Vin Diesel le Rapide", "Jason Statham le Transporteur",
    "Robert Downey Jr Iron Man", "Chris Evans Captain", "Chris Hemsworth Thor", "Scarlett Johansson Widow",
    "Angelina Jolie la Rebelle", "Jennifer Lawrence la Flamme", "Emma Watson la Sage", "Margot Robbie la Folle",
    "Keanu Reeves l'Élu", "Nicolas Cage le Trésor", "Samuel L Jackson le Badass", "Morgan Freeman la Voix",
    "Denzel Washington le Protecteur", "Al Pacino le Parrain", "Robert De Niro le Taureau", "Meryl Streep la Reine",
    "Viola Davis la Puissante", "Idris Elba le Charisme", "Tom Hardy le Venimeux", "Cillian Murphy le Peaky",
    "Ryan Gosling le Ken", "Zac Efron le Sportif", "Zendaya l'Icône", "Tom Holland l'Araignée",
    "Millie Bobby Brown l'Étrange", "Henry Cavill le Superman", "Gal Gadot la Wonder", "Jason Momoa l'Aquaman",
    "Benedict Cumberbatch le Sherlock", "Jared Leto le Joker", "Joaquin Phoenix le Clown", "Heath Ledger la Légende",
    "Christian Bale le Chevalier Noir", "Hugh Jackman le Wolverine", "Ryan Reynolds le Deadpool", "Jackie Chan le Cascadeur",
    "Jet Li le Maître", "Bruce Lee la Légende", "Chuck Norris l'Invincible", "Arnold Schwarzenegger le Terminator",
    "Sylvester Stallone le Rocky", "Jean-Claude Van Damme le Muscle", "Steven Seagal l'Immobile", "Danny Trejo le Machete",
    "Samuel Le Bihan le Badass", "Omar Sy le Lupin", "Jean Dujardin l'Artiste", "Vincent Cassel le Mesrine",
    "Marion Cotillard la Môme", "Sophie Marceau la Belle", "Léa Seydoux la Bond Girl", "Gérard Depardieu l'Ogre",
    "Alain Delon le Samouraï", "Jean-Paul Belmondo le Magnifique", "Louis de Funès le Génie", "Coluche l'Enfoiré",
    "Zinedine Zidane le Divin", "Kylian Mbappé le Génie", "Karim Benzema le Ballon d'Or", "Thierry Henry la Légende",
    "Didier Drogba l'Icône", "Samuel Eto'o le Lion", "Rihanna la Reine", "Beyoncé la Queen", "Jay-Z le Boss",
    "Kanye West le Ye", "Drake le Champagne Papi", "Travis Scott la Flamme", "Kendrick Lamar le King",
    "Eminem le Slim Shady", "50 Cent le Bulletproof", "Snoop Dogg le Relax", "Dr Dre le Producteur",
    "Justin Bieber le Baby", "Selena Gomez la Douce", "Ariana Grande la Diva", "Taylor Swift l'Éternelle",
    "Lady Gaga la Monster", "Katy Perry la Fireworks", "Billie Eilish l'Alternative", "Dua Lipa la Star",
    "The Weeknd l'Abel", "Post Malone le Tatoué", "Bad Bunny le Conejo", "J Balvin le Latino",
    "Elon Musk le Martien", "Jeff Bezos l'Amazon", "Mark Zuckerberg le Meta", "Bill Gates le Windows",
    "Steve Jobs l'Apple", "Cristiano Ronaldo le GOAT", "Lionel Messi la Pulga", "Michael Jordan le Jumpman",
    "LeBron James le King", "Kobe Bryant la Mamba", "Stephen Curry le Sniper", "Tiger Woods le Tigre",
    "Roger Federer l'Élégant", "Rafael Nadal le Taureau", "Novak Djokovic le Djoker", "Usain Bolt l'Éclair",
    "Lewis Hamilton le Champion", "Max Verstappen le Hollandais Volant", "Conor McGregor le Notorious",
    "Mike Tyson l'Iron Mike", "Muhammad Ali le Greatest", "Floyd Mayweather le Money", "Francis Ngannou le Prédateur",
    "Aya Nakamura la Djadja", "Gims le Sapé", "Booba le Duc", "Kaaris le Dozo", "Damso le Dems",
    "Ninho le NI", "Jul le J", "SCH le S", "Orelsan le Civilisé", "Angèle la Belge",
    "Stromae le Maestro", "Céline Dion la Voix", "Johnny Hallyday l'Idole", "David Guetta le DJ",
    "DJ Snake le Serpent", "Kylian Mbappé le Kid de Bondy", "Paul Pogba la Pioche", "Antoine Griezmann Grizou",

    # --- JEUX VIDÉO & FICTION (150) ---
    "Mario le Plombier", "Luigi le Vert", "Link le Héros", "Zelda la Princesse", "Ganondorf le Sombre",
    "Pikachu l'Électrique", "Dracaufeu le Brûlant", "Mewtwo le Psychique", "Sonic le Rapide", "Knuckles le Fort",
    "Kratos le Dieu de la Guerre", "Atreus le Fils", "Joel le Survivant", "Ellie l'Immunisée", "Nathan Drake le Chasseur",
    "Lara Croft l'Exploratrice", "Master Chief le Major", "Cortana l'IA", "Marcus Fenix le Gears", "Doom Slayer l'Enfer",
    "Geralt de Riv le Sorceleur", "Ciri l'Enfant de Sang Noir", "Yennefer la Magicienne", "Triss la Rousse", "Dandelion le Barde",
    "Arthur Morgan le Hors-la-loi", "John Marston le Cowboy", "Dutch van der Linde le Plan", "Solid Snake l'Espion", "Liquid Snake le Frère",
    "Big Boss le Soldat", "Raiden le Ninja Blanc", "Cloud Strife le Mercenaire", "Sephiroth l'Ange Déchu", "Tifa la Combattante",
    "Aerith la Fleuriste", "Sora le Porteur", "Riku l'Ombre", "Kairi la Lumière", "Leon Kennedy le Survivant",
    "Jill Valentine la S.T.A.R.S", "Chris Redfield le Roc", "Albert Wesker le Traître", "Ezio Auditore l'Assassin", "Altaïr le Premier",
    "Connor Kenway le Guerrier", "Edward Kenway le Pirate", "Bayek le Protecteur", "Kassandra la Mercenaire", "Eivor le Viking",
    "Steve le Mineur", "Alex la Survivante", "Creeper l'Explosif", "Enderman le Téléporteur", "Herobrine le Mythe",
    "Sans le Squelette", "Papyrus le Frère", "Frisk l'Enfant", "Toriel la Maman", "Asgore le Roi",
    "Cj de Grove Street", "Big Smoke le Traître", "Tommy Vercetti le Parrain", "Nico Bellic le Cousin", "Franklin le Braqueur",
    "Michael le Retraité", "Trevor le Fou", "Lester le Cerveau", "Agent 47 le Tueur", "Sam Fisher l'Ombre",
    "Gordon Freeman le Scientifique", "G-Man le Mystère", "Chell la Sujette", "Glados l'IA Folle", "Wheatley le Robot",
    "Heavy le Gros", "Spy l'Espion Français", "Scout le Rapide", "Medic le Docteur", "Pyro l'Incendiaire",
    "Tracer la Rapide", "Genji le Cyborg", "Hanzo l'Archer", "Reinhardt le Bouclier", "Mercy la Soigneuse",
    "Jinx la Folle", "Vi la Punisseuse", "Yasuo le Vent", "Ahri la Renarde", "Lux la Lumière",
    "Master Yi l'Épéiste", "Teemo le Diable", "Lee Sin l'Aveugle", "Zed l'Ombre", "Katarina la Lame",
    "Scorpion le Brûlé", "Sub-Zero le Glacé", "Raiden le Dieu du Tonnerre", "Liu Kang le Champion", "Johnny Cage l'Acteur",
    "Sonya Blade la Colonelle", "Jax le Bras d'Acier", "Mileena la Vorace", "Kitana la Princesse", "Baraka le Guerrier",
    "Dante le Chasseur", "Vergil le Frère Sombre", "Nero le Bras de Diable", "Bayonetta la Sorcière", "Jeanne la Rivale",
    "Spyro le Dragon", "Crash Bandicoot le Fou", "Coco Bandicoot la Génie", "Dr Neo Cortex le Maléfique", "Aku Aku le Masque",
    "Ratchet le Lombax", "Clank le Petit Robot", "Jak le Guerrier Eco", "Daxter la Bellette", "Sly Cooper le Voleur",
    "Parappa le Rappeur", "Rayman le Sans-Bras", "Globox le Bleu", "Pac-Man le Glouton", "Ms Pac-Man la Dame",
    "Donkey Kong le Gorille", "Diddy Kong le Petit", "King K Rool le Croco", "Samus Aran la Chasseuse", "Ridley le Monstre",
    "Fox McCloud le Pilote", "Falco Lombardi l'As", "Captain Falcon le Bolide", "Kirby la Boule Rose", "Meta Knight le Masqué",
    "King Dedede le Pingouin", "Villager le Maire", "Isabelle la Secrétaire", "Tom Nook le Marchand", "Resetti la Taupe"
]
